version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    stop_signal: SIGINT
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "admin"
      DB_NAME: crypto_analysis

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crypto_analysis
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-files/db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql
    expose:
      - 3306
      
volumes:
  db-data: