version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_DB: crypto_analysis

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 14142135
      MYSQL_DATABASE: crypto_analysis
    volumes:
      - ./docker-files/db:/docker-entrypoint-initdb.d
