version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    stop_signal: SIGINT
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "admin"
      DB_NAME: crypto_analysis

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 14142135
      MYSQL_DATABASE: crypto_analysis
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
      - 33060

volumes:
  db-data: