version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    stop_signal: SIGINT
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "admin"
      DB_NAME: crypto_analysis

  db:
    image: mysql:8.0.33
    build:
      context: ./docker-files/db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
      - 33060

volumes:
  db-data: {}