name: Deploy Jekyll with Tailwind CSS to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          gem install jekyll
          gem install jekyll-feed
          gem install jekyll-seo-tag
          npm install

      - name: Build with Jekyll and Tailwind CSS
        run: |
          bundle exec jekyll build
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
